### ISSUE TITLE
How can i receive the response?

### ISSUE THREAD

**Issue by hsyan2008** [Clever/gearman#11]
How can i receive the response?

**Comment by natebrennand** [comment]
[`func (c *Client) Submit(fn string, payload []byte, data, warnings io.WriteCloser) (*job.Job, error)`](https://godoc.org/github.com/Clever/gearman#Client.Submit)

The WORK_DATA packets are written to the `data io.WriteCloser` parameter. WORK_WARNING packets are written to the `warnings io.WriteCloser`. If `nil` is provided for either the relevant data will just be ignored. Passing a [`bytes.buffer`](https://golang.org/pkg/bytes/#Buffer) (or any other `io.WriteCloser`) in for either parameters will work.
References to both of these `io.WriteCloser`'s are also kept in the `Job` returned by `Submit`.

-----

Let me know if there is anything else I can explain!
